all:
  hosts:
    oracle-xe.example.com:
  
  vars:
    oracle:
      install_zip_file: "oracle-xe-11.2.0-1.0.x86_64.rpm.zip"
      install_dir_local: "./files/"
      install_dir_remote: "/root/oracle"

