all:
  hosts:
    openstack:
      ansible_connection: local

    oracle-xe.example.com:
      ansible_user: centos
      ansible_become: yes
  
  vars:
    oracle:
      install_zip_file: "oracle-xe-11.2.0-1.0.x86_64.rpm.zip"
      install_dir_local: "./files/"
      install_dir_remote: "/install/oracle"

