CREATE BIGFILE TABLESPACE tbs_data DATAFILE '/u01/app/oracle/oradata/XE/tbs_data_01.dbf' SIZE 100M AUTOEXTEND ON;
CREATE BIGFILE TABLESPACE tbs_index DATAFILE '/u01/app/oracle/oradata/XE/tbs_index_01.dbf' SIZE 100M AUTOEXTEND ON;

CREATE USER silvio IDENTIFIED BY oracle DEFAULT TABLESPACE tbs_data;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE, CREATE ANY DIRECTORY TO silvio;

CONN silvio/oracle@xe;

CREATE TABLE person(
  id   INTEGER       NOT NULL PRIMARY KEY,
  name VARCHAR2(100) NOT NULL
);

INSERT INTO person(id, name) VALUES(1, 'NAME #1');
INSERT INTO person(id, name) VALUES(2, 'NAME #2');
INSERT INTO person(id, name) VALUES(3, 'NAME #3');

COMMIT;

EXIT;
